language: node_js

node_js:
    - node

services: 
    - mongodb
    - docker

before_script:
    - docker-compose up -d db frontend-test backend-test

script:
    - cd ./backend
    - npm run test
    - cd ..
    - cd ./frontend
    - npm run end-to-end-test