language: node_js

node_js:
    - node

services: 
    - docker

before_script:
    - npm install --global cross-env
    - docker-compose build
    - docker-compose up -d db frontend-test backend-test

script:
    - cd ./backend
    - sudo npm install
    - sudo npm run test
    - cd ..
    - cd ./frontend
    - sudo npm install
    - sudo npm run end-to-end-test