language: node_js

service: 
    - mongodb

env:
    - MONGOLAB_URI=mongodb://localhost:27017/footapp

before_script:
    - mongo footapp --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
    - cd ./backend
    - npm install
    - cd ..
    - cd ./frontend
    - npm install


script:
    - cd ./backend
    - npm run production
    - cd ..
    - cd ./frontend
    - npm run production
    - npm run start
    - cd ..
    - cd ./backend
    - npm run test
    - cd ..
    - cd ./frontend
    - npm run end-to-end-test