version: '3'

services:
    db:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - ./data:/data/db
    backend-dev:
        build: 
            context: ./backend
            dockerfile: Dockerfile-backend.dev
        ports:
            - '3003:3003'
        expose:
            - 3003
        depends_on:
            - db
        container_name: 'footapp-backend-dev'
        volumes: 
            - ./backend:/backend
            - /backend/node_modules
    frontend-dev:
        build: 
            context: ./frontend
            dockerfile: Dockerfile-frontend.dev
        ports:
            - '8081:8081'
        expose:
            - 8081
        container_name: 'footapp-frontend-dev'
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
    backend-test:
        build: 
            context: ./backend
            dockerfile: Dockerfile-backend.test
        ports:
            - '3003:3003'
        expose:
            - 3003
        depends_on:
            - db
        container_name: 'footapp-backend-test'
        volumes: 
            - ./backend:/backend
            - /backend/node_modules
    frontend-test:
        build: 
            context: ./frontend
            dockerfile: Dockerfile-frontend.test
        ports:
            - '8081:8081'
        expose:
            - 8081
        container_name: 'footapp-frontend-test'
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules