import 'modules/font-awesome/css/font-awesome.min.css'
import 'modules/ionicons/dist/css/ionicons.min.css'
import 'modules/bootstrap/dist/css/bootstrap.min.css'
import 'modules/bootstrap/dist/js/bootstrap.min.js'

import '../../main/app.css'
import '../../auth/auth.css'
import '../../resetPassword/resetPassword.css'
import '../../newPassword/newPassword.css'
import './header.css'
import './sidebar.css'
import '../../home/home.css'
import '../../profile/profile.css'